<?php
defined('ABSPATH') || exit;
class SuperWoo_Cart_Recovery_Automation {
    private $repo; private $email; private $conditions;
    public function __construct($repo,$email) { $this->repo=$repo; $this->email=$email; $this->conditions=new SuperWoo_Cart_Recovery_Conditions(); }
    public function hooks() { add_action('superwoo_cart_recovery_run_execution',[$this,'run']); }
    public function start($cart) { foreach($this->repo->workflows(true) as $workflow) { if ('cart_abandoned'!==$workflow['trigger_type']) continue; $id=$this->repo->create_execution((int)$cart['id'],(int)$workflow['id']); if($id&&function_exists('as_enqueue_async_action')) as_enqueue_async_action('superwoo_cart_recovery_run_execution',[$id],'superwoo-cart-recovery'); } }
    public function run($execution_id) { $execution=$this->repo->execution($execution_id); if(!$execution||!$this->repo->claim_execution($execution_id)) return; $cart=$this->repo->find_cart((int)$execution['cart_id']); if(!$cart||in_array($cart['status'],['recovered','expired','unsubscribed','suppressed'],true)){ $this->repo->update_execution($execution_id,['status'=>'cancelled','locked_at'=>null]); if($cart)$this->repo->event((int)$cart['id'],'automation_stopped'); return; }
        $workflow=null;foreach($this->repo->workflows() as $candidate){if((int)$candidate['id']===(int)$execution['workflow_id']){$workflow=$candidate;break;}} if(!$workflow||!$this->conditions->matches($cart,$this->repo->items((int)$cart['id']),json_decode($workflow['conditions'],true))){$this->repo->update_execution($execution_id,['status'=>'completed','completed_at'=>$this->repo->now(),'locked_at'=>null]);$this->repo->event((int)$cart['id'],'automation_step_skipped_conditions');return;} $steps=$this->repo->steps((int)$execution['workflow_id']); $index=0; foreach($steps as $i=>$step){if((int)$step['id']===(int)$execution['current_step_id']){$index=$i;break;}} $step=$steps[$index]??null; if(!$step){$this->repo->update_execution($execution_id,['status'=>'completed','completed_at'=>$this->repo->now(),'locked_at'=>null]);$this->repo->event((int)$cart['id'],'automation_completed');return;}
        $config=json_decode($step['configuration'],true)?:[]; $type=$step['action_type']; if('wait'===$type){$delay=max(0,absint($config['minutes']??0))*MINUTE_IN_SECONDS;$next=$steps[$index+1]['id']??0;$this->repo->update_execution($execution_id,['status'=>'waiting','current_step_id'=>$next,'next_run_at'=>gmdate('Y-m-d H:i:s',time()+$delay),'locked_at'=>null]); if(function_exists('as_schedule_single_action'))as_schedule_single_action(time()+$delay,'superwoo_cart_recovery_run_execution',[$execution_id],'superwoo-cart-recovery');$this->repo->event((int)$cart['id'],'automation_step_scheduled');return;}
        if('send_email'===$type){$token=wp_generate_password(48,false,false);$this->repo->update_status((int)$cart['id'],'recovery_in_progress',['recovery_token_hash'=>$this->repo->hash($token),'recovery_token_expires_at'=>gmdate('Y-m-d H:i:s',time()+7*DAY_IN_SECONDS)]);$this->email->send($this->repo->find_cart((int)$cart['id']),add_query_arg('superwoo_recover',$token,home_url('/')));}
        $next=$steps[$index+1]['id']??0;$this->repo->update_execution($execution_id,['status'=>$next?'pending':'completed','current_step_id'=>$next,'locked_at'=>null,'completed_at'=>$next?null:$this->repo->now()]); if($next&&function_exists('as_enqueue_async_action'))as_enqueue_async_action('superwoo_cart_recovery_run_execution',[$execution_id],'superwoo-cart-recovery');
    }
}
